backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow
media_folder: "src/images"

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "content/about" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "about" # Filename template, e.g., about.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "About Us Paragraphs",
          name: aboutUsParagraphs,
          widget: list,
          create: true,
          field: { label: paragraph, name: paragraph, widget: text },
        }
      - {
          label: "Header Images",
          name: headerImages,
          widget: list,
          create: true,
          field:
            {
              label: image,
              name: image,
              widget: image,
              choose_url: true,
              default: "/src/images/basil.jpg",
              media_library: { config: { multiple: false } },
            },
        }
      - {
          label: "Major Markets",
          name: "majorMarkets",
          widget: list,
          create: true,
          field: { label: "country", name: countryName, widget: "string" },
        }
      - {
          label: "Our Team Paragraphs",
          name: ourTeamParagraphs,
          widget: list,
          create: true,
          field: { label: paragraph, name: paragraph, widget: text },
        }
      - {
          label: "Team Hero Image",
          name: teamHeroImage,
          widget: image,
          choose_url: true,
          default: "/src/images/basil.jpg",
        }
      - {
          label: "Team Members",
          name: teamMembers,
          widget: list,
          create: true,
          field:
            {
              label: member,
              name: member,
              widget: object,
              fields:
                [
                  { label: "Member Image", name: memberImage, widget: image },
                  { label: "Member Name", name: memberName, widget: string },
                  {
                    label: "Member Designation",
                    name: memberDesignation,
                    widget: string,
                  },
                ],
            },
        }

  - name: "manufacturing" # Used in routes, e.g., /admin/collections/blog
    label: "Manufacturing" # Used in the UI
    folder: "content/about/manufacturing" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "manufacturing" # Filename template, e.g., about.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "para1", name: "para1", widget: "text" }
      - { label: "para2", name: "para2", widget: "text" }
      - { label: "para3", name: "para3", widget: "text" }
      - { label: "para4", name: "para4", widget: "text" }

  - name: "product_catgories"
    folder: "content/products/productCategories"
    label: "Product Categories"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "name", name: "name", widget: "string", required: true }
      - { label: "id", name: "id", widget: "string", required: true }
      - {
          label: "description",
          name: "description",
          widget: "text",
          required: true,
        }

  - name: "Product"
    folder: "content/productList"
    create: true
    slug: "{{slug}}"
    label: "Products"
    fields:
      - { label: name, name: name, widget: string }
      - { label: title, name: title, widget: string }
      - {
          label: details,
          name: details,
          widget: list,
          create: true,
          field:
            {
              label: "detail",
              name: "detail",
              widget: object,
              fields:
                [
                  { label: key, name: key, widget: string },
                  { label: value, name: value, widget: string },
                ],
            },
        }
      - {
          label: Description,
          name: description,
          widget: markdown,
          required: true,
        }
      - {
          label: "Manufacturing Details",
          name: manufacturing_details,
          widget: list,
          create: true,
          field: { label: detail, name: detail, widget: markdown },
        }
      - { label: "Show on home", name: showOnHome, widget: boolean }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: image,
          choose_url: true,
          default: "/src/images/basil.jpg",
          media_library: { config: { multiple: false } },
        }
      - {
          label: Category,
          name: category,
          widget: "relation",
          required: true,
          collection: "product_catgories",
          value_field: "name",
          search_fields: ["name"],
          display_fields: ["name"],
        }

  - name: "Blogs"
    folder: "content/blogs/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    label: "Blog"
    fields:
      - { label: name, name: name, widget: string }
      - { label: title, name: title, widget: string }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: Heading, name: heading, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: Category,
          name: category,
          widget: "relation",
          required: true,
          collection: "blog_categories",
          value_field: "name",
          search_fields: ["name"],
          display_fields: ["name"],
        }

  - name: "blog_categories"
    folder: "content/blogs/categories"
    label: "Blog Categories"
    create: true
    slug: "{{id}}"
    fields:
      - { label: "name", name: "name", widget: "string", required: true }
      - { label: "id", name: "id", widget: "string", required: true }

  - name: "Home"
    folder: "content/home"
    label: "Home"
    fields:
      - { label: heading1, name: heading1, widget: string, required: true }
      - { label: heading2, name: heading2, widget: string, required: true }
      - { label: heading3, name: heading3, widget: string, required: true }
